### ISSUE TITLE
html和body的height:100%差别(由fullpage全屏的联想)

### ISSUE THREAD

**Issue by thecatshidog** [thecatshidog/blog#2]
我们经常hi遇到一个实际的问题，就是让一个div全屏显示。

```css
div{
    width:100%;
    height:100%;
}
```

这样的代码是不起任何效果的,就算把body也加上100%也是无效的

```css
div{
    width:100%;
    height:100%;
    position:absolute;
    top:0;
    left:0;
}

```

对div使用上面的代码就可以使div全屏了。

还有一种方法：

```css
html,body{
    width:100%;
    height:100%;
}
```
对html设置了100%的高度也就成功了。

上面的postion:absolute;也是相对于html才能是100%占满全屏。如果有其他的父元素是relative或者absolute的状态，那么也会影响这个div。

那么我想一个问题为什么对html设置100%height就可以成功全屏，而body却不行呢。

1、html尺寸由浏览器窗口控制；

2、几乎所有的浏览器默认的margin都是设置在body上的。

3、html{overflow:auto;}是默认的情况；

所以我们知道了我们平时设置高度是用内容撑开了html的高度，而如果对html使用overflow：hidden的话，那么溢出浏览器屏幕100%窗口的就将会被隐藏掉。也就是说，html的宽高等于浏览器窗口的宽高。
